### ISSUE TITLE
Documentation needs 6.0 X-Pack additions

### ISSUE THREAD

**Issue by derickson** [elastic/elasticsearch-docker#102]
Using ```docker.elastic.co/elasticsearch/elasticsearch:6.0.0-beta1``` instructions here ```https://www.elastic.co/guide/en/elasticsearch/reference/6.0/docker.html#docker``` causes the new bootstrap defaults to fail.

>ERROR: [3] bootstrap checks failed
[1]: Default SSL key and certificate do not provide security; please generate keys and certificates
[2]: Please set a passphrase using the elasticsearch-keystore tool for the setting [xpack.security.authc.token.passphrase] that is at least 8 characters in length and does not match the default passphrase or disable the token service using the [xpack.security.authc.token.enabled] setting
[3]: HTTPS is required in order to use the token service. Please enable HTTPS using the [xpack.security.http.ssl.enabled] setting or disable the token service using the [xpack.security.authc.token.enabled] setting.

Let me know if this really should go somewhere else

**Comment by dliappis** [comment]
Hey @derickson thanks for your interest in the beta1 pre-release! The instructions have not been updated yet; note that we do not recommend running `-alpha` and `-beta` pre-release versions on production, as mentioned in the ES logs.

Meanwhile, the TL;DR until the docs have been updated is:

- Default password with x-pack.security 6.0 [has been disabled](https://www.elastic.co/guide/en/x-pack/6.0/setting-up-authentication.html#disabling-default-password). For the Docker images, you can bootstrap the password for the `elastic` user through the env var `ELASTIC_PASSWORD`, see: https://github.com/elastic/elasticsearch-docker/blob/6.0/build/elasticsearch/bin/es-docker#L44
This only bootstrap a password if the node is not joining a cluster where a password for elastic has already been created in the security index.

- You'll need to configure TLS for transport using the [instructions here](https://www.elastic.co/guide/en/x-pack/6.0/ssl-tls.html). This requires creating a CA (or using an existing CA if you have one) and certificates+keys per node and configured as shown [here](https://www.elastic.co/guide/en/x-pack/6.0/ssl-tls.html#enable-ssl). For the sake of the getting started experience with Docker and development, we have provided also the possibility to use the env var `ALLOW_INSECURE_DEFAULT_TLS_CERT=true` as shown here: https://github.com/elastic/elasticsearch-docker/blob/6.0/build/elasticsearch/bin/es-docker#L52 but please (PLEASE!) make sure that you do not use this in production environments.

We are working on the documentation for those features, including different ways of customization, as well as additional features to come, so stay tuned and thank you for your patience!

**Comment by dliappis** [comment]
This should has been addressed with the 6.0.0 GA.
