### ISSUE TITLE
Unable to connect two nodes running on two different machine which are not in the same network

### ISSUE THREAD

**Issue by JinnaBalu** [elastic/elasticsearch-docker#105]
Host 1 : 0.0.122.211

Host 2: 0.0..143.68

here are my docker-compose files which i am running on two hosts

[Docker-compose for two host](https://github.com/JinnaBalu/dev-ops/tree/master/docker-elasticsearch/two-nodes)

**Comment by jarpy** [comment]
The image you are using is `elasticsearch:2.4.1` which is an older image maintained by Docker Inc. Our (Elastic's) official images are available from version 5 onward as `docker.elastic.co/elasticsearch/elasticsearch:$VERSION`. I'm not sure how configuration via environment variables works with their images, but what you have looks OK for ours.

I would, however, also set `minimum_master_nodes=2` to prevent the nodes from starting up in a split-brained state.

**Comment by jarpy** [comment]
Oh, and since you are mapping ports 9200,9300 through to the host systems, you want to use the host system addresses for the Zen discovery settings too.

**Comment by JinnaBalu** [comment]
this helped me solving my requirements 

https://stackoverflow.com/questions/28632977/elasticsearch-in-docker-container-cluster#answer-29269865

And thank you for your suport too.

Current configuration in my docker-compose works fine.

**Comment by jarpy** [comment]
Great. Sorry I was slow in getting to you. Glad it's all working now!
