### ISSUE TITLE
ES_JAVA_OPTS heap example

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-docker#11]
Minor doc issue:

>Use the env var ES_JAVA_OPTS to set heap size, e.g. to use 16GB use -e ES_JAVA_OPTS="-Xms16g -Xmx=16g" with docker run. It is also recommended to set a memory limit for the container.

The above has an extra = which makes the Xmx value invalid for the JVM, should be just -Xmx16g :)

While we are on the topic of heap size, I wonder if it makes sense to call out https://github.com/elastic/elasticsearch-docker/issues/8 in the doc.  I expect more folks to run into this when developing on small server/laptop with limited memory, for the boot2docker can often default to a little less than 1G - which means that it will always throw the `# Native memory allocation (mmap) failed to map 2060255232 bytes for committing reserved memory.` error in these environments since the default ES_HEAP_SIZE of Elasticsearch has been [increased to 2G](https://github.com/elastic/elasticsearch/pull/18311) starting in ES 5.0.

**Comment by dliappis** [comment]
@ppf2 Good catch! Fixed by https://github.com/elastic/elasticsearch-docker/commit/eac2bd70f68c6b286ef7b99d8e896fdf7bcbaf3b

For #8 yes I think it makes sense to mention it in the OSX with Docker Toolbox section, at least until everyone moves out of docker toolbox into the native Docker.
