### ISSUE TITLE
Can't externalize volume /usr/share/elasticsearch/data

### ISSUE THREAD

**Issue by hadfoo** [elastic/elasticsearch-docker#111]
## Feature Description
I create a container for volumes :
`docker create --name es-data -v /var/lib/docker/elasticsearch:/usr/share/elasticsearch/data busybox`

And I create the ElasticSearch container :
`docker create --name es-server --volumes-from es-data -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.5.2`

But when I start the container, it stops with a java.nio.file.AccessDeniedException.

Docker searches for the /usr/share/elasticsearch/data/nodes folder which should contain files. But given that we mapped the parent directory with an empty folder in es-data, Elastic Search fails to start.

**Comment by dliappis** [comment]
Hey! Thanks for your interest in the image.

In this setup, your local directory under `/var/lib/docker/elasticsearch` would need to be owned by `1000:1000` (see the [important note in the docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docker.html#_b_bind_mounted_configuration)).

One alternative would be to use a [docker named volume](https://success.docker.com/KBase/Different_Types_of_Volumes) and just run with:

```
docker create --name es-server -v es-data:/usr/share/elasticsearch/data -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.5.2
```

Docker will automatically create the volume es-data, you won't have to tinker with permissions and can always inspect the contents of this volume with:

```
$ docker run --rm -v es-data:/es-data -ti centos:7 /bin/bash -c 'ls -la /es-data'
total 12
drwxr-xr-x 3 1000 1000 4096 Sep  5 10:40 .
drwxr-xr-x 1 root root 4096 Sep  5 10:42 ..
drwxr-xr-x 3 1000 1000 4096 Sep  5 10:40 nodes
```

##### Note:

There is an alternative to `-v` which is `--mount`, achieving the same result, you can see the differences here: https://docs.docker.com/engine/admin/volumes/volumes/#start-a-container-with-a-volume

**Comment by hadfoo** [comment]
Fine, thank you very much :)
