### ISSUE TITLE
Unable to start elasticsearch:5.6.3 container

### ISSUE THREAD

**Issue by adamschmidt** [elastic/elasticsearch-docker#126]
## Bug Description

Docker image: elasticsearch:5.6.3
Docker version: 17.06.0-ce, build 02c1d87
Host os: Linux api 4.4.74-boot2docker #1 SMP Mon Jun 26 18:01:14 UTC 2017 x86_64 GNU/Linux
`docker info` output:

```
Containers: 21
 Running: 0
 Paused: 0
 Stopped: 21
Images: 93
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 176
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.74-boot2docker
Operating System: Boot2Docker 17.06.0-ce (TCL 7.2); HEAD : 0672754 - Thu Jun 29 00:06:31 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8MiB
Name: api
ID: 5RL7:MOKB:UAAC:C47P:2J5T:ZD75:DPMP:ENI5:5K4Q:MXUC:ZCV5:T4KE
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 25
 System Time: 2017-10-11T02:10:14.727279766Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

## Steps to Reproduce

* Pull the container using `docker pull docker.elastic.co/elasticsearch/elasticsearch:5.6.3`
* Try to run the container using `docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:5.6.3`

Fails with the following:

```
docker: Error response from daemon: linux spec user: unable to find user elasticsearch: no matching entries in passwd file.
ERRO[0000] error getting events from daemon: net/http: request canceled 
```

**Comment by dliappis** [comment]
I haven't been able to reproduce this and I am not sure what is your host operating system (Mac OS? Windows?).
I can see you are using boot2docker, note that if you downloaded the installer from the [github repo](https://github.com/boot2docker/windows-installer/releases) it is deprecated and you should be installing the [Docker Toolbox](https://www.docker.com/toolbox) instead.

On a Windows laptop, I uninstalled "Docker for Windows" I already had there, disabled hyper-v and installed the [Docker Toolbox](https://www.docker.com/products/docker-toolbox). I increased the memory for the VM created, by doing `docker-machine stop` and then adjusting the memory for the VM in the VirtualBox UI. Afterwards I executed `docker-machine start`' and was able to run Elasticsearch with the above command (`docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:5.6.3`) without issues.

Finally note that Docker Toolbox is not something we frequently use here, if you are anyway running Virtualbox IMHO you will be better off running a normal Linux distribution with Docker installed in it. [Docker for Windows](https://docs.docker.com/docker-for-windows/install/) / [Docker for Mac](https://docs.docker.com/docker-for-mac/install/) is what most users will run on those platforms anyway (unless you are on Windows Home and [can't have hyper-v](https://forums.docker.com/t/installing-docker-on-windows-10-home/11722/5)).

**Comment by adamschmidt** [comment]
Thanks @dliappis - I'm using Docker Toolkit on MacOS, with docker-machine backed by VirtualBox.

**Comment by adamschmidt** [comment]
After updating to the latest version of Docker Toolbox (17.09.0-ce), creating a new machine (updated the boot2docker ISO in the process), then pulling the container to the fresh machine, I was able to start the container.

FWIW, the new output of `docker info` is:

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.89-boot2docker
Operating System: Boot2Docker 17.09.0-ce (TCL 7.2); HEAD : 06d5c35 - Wed Sep 27 23:22:43 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.696GiB
Name: elastic
ID: R7WY:UJQV:2BNC:PDRD:FTU5:4N5I:KSLR:AYU4:3W36:V5JG:56OG:4IAB
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 27
 System Time: 2017-10-12T01:08:36.565998999Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by dliappis** [comment]
Great to hear you got it working
