### ISSUE TITLE
[feature] apply license automatically when container was started.

### ISSUE THREAD

**Issue by sho-suzuki** [elastic/elasticsearch-docker#128]
Hi all.
## Feature Description

1. add license file to the  elasticsearch image  
ex) Dockerfile  
```bash
FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.0
WORKDIR /usr/share/elasticsearch
COPY license.json license.json
```
2. build customized elasticsearch image.
ex) docker-compose build elasticsearch

3. start container and apply license automatically.
ex) docker-compose up -d elasticsearch

->I want to execute apply license request automatically in the start up shell like  bin/es-docker.
ex) `curl --noproxy elasticsearch http://elasticsearch:9200/_xpack/license\?acknowledge\=true -H "Content-Type: application/json" -d @license.json`

I had rewrite es-docker, but doesn't work.

```diff
- exec bin/elasticsearch "${es_opts[@]}"
+ # start elasticsearch, wait 10 sec, and apply license 
+ bin/elasticsearch "${es_opts[@]}" && wait 10 && curl --noproxy elasticsearch http://elasticsearch:9200/_xpack/license\?acknowledge\=true -H "Content-Type: application/json" -d @license.json
```

any ideas?

**Comment by jarpy** [comment]
> `bin/elasticsearch "${es_opts[@]}" && wait 10 && curl`

This says:
1. Start Elasticsearch
2. After Elasticsearch has exited, if it was successful, wait for 10 seconds
3. After that, use curl to apply the licence

The problem is that Elasticsearch doesn't exit, because it's the main process of the container.

You might want something more like:

`(wait 10 && curl... ) & bin/elasticsearch "${es_opts[@]}"` 

Which says:
1. In the background, wait ten seconds and then try apply the licence.
2. _Meanwhile_ start up Elasticsearch

Personally, I would avoid all of this and apply the licence by running curl in another, short-lived container. I'd also avoid using a hard-coded sleep. Instead you could do something like:

```bash
ES='http://elasticsearch:9200'

# Wait for Elasticsearch to start up before doing anything.
until curl -s -o /dev/null ${ES}; do
    echo Waiting for Elasticsearch...
    sleep 1
done

curl \
  --noproxy '*' \
  -H 'Content-Type: application/json' \
  -d @license.json \
  "${ES}/_xpack/license?acknowledge=true" 
```

**Comment by sho-suzuki** [comment]
@jarpy thanks for your fast reply!

I forgot apply license to the container sometimes.
so I would automated it.

I rewrited the es-docker using your suggestion.
and then, it worked.

```diff
- exec bin/elasticsearch "${es_opts[@]}"
+ ES='http://elasticsearch:9200'
+ # Wait for Elasticsearch to start up before doing anything.
+ (until curl --noproxy '*' -s -o /dev/null ${ES}; do
+    echo Waiting for Elasticsearch...;
+    sleep 1;
+ done;
+ curl \
+  --noproxy '*' \
+  -H 'Content-Type: application/json' \
+ -d @license.json \
+ "${ES}/_xpack/license?acknowledge=true"
+ ) & bin/elasticsearch "${es_opts[@]}"
```

Thank you very much.

**Comment by jarpy** [comment]
Nice! Glad I could help.

**Comment by briananderson1222** [comment]
@jarpy Why can't this just be supported through an xpack security setting or is it already? https://www.elastic.co/guide/en/elasticsearch/reference/6.2/security-settings.html . I'd think we'd be able to mount the license.. specify it's location in the security settings and elasticsearch could figure out how to load it.. Why is this not the case?
