### ISSUE TITLE
Provide v6 RC images from registry

### ISSUE THREAD

**Issue by dkarlovi** [elastic/elasticsearch-docker#130]
## Feature Description

Currently, I see master (going toward 6.0.0) works on Openshift, current stable does not. As I'm in a pre-integration phase with my app, a RC version of ES is just fine with me, it'll be some time before my app is out and I'll lock down versions much later than now.

It would be quite handy if you made RC images available in your registry too.

**Comment by dkarlovi** [comment]
I can see image `docker.elastic.co/elasticsearch/elasticsearch-platinum:6.0.0-rc1` is made available, not really sure how to discover others if available.

**Comment by dliappis** [comment]
@dkarlovi Thanks for your interest towards the images and =the latest changes towards Openshift compatibility.

At the moment there are no images that have been pushed with those features, `6.0.0-rc2` will include them.

In the mean time, you can just checkout this repo, set the env var `ELASTIC_VERSION=6.0.0-rc1` and just execute `make` from within the 6.0 or master branch. (It will also execute the tests, will take a bit).

You will end up with three images, one with the basic license, one with trial platinum and a plain oss version. You can use any, I'd suggest you start with the `elasticsearch-basic:6.0.0-rc1` image which includes the free basic license and gives you some x-pack features (details [here](https://www.elastic.co/subscriptions)).

**Comment by dkarlovi** [comment]
@dliappis thanks for your reply.

It's good to have the option to do it yourself, but the way I see it, you're building those images as part of your pipeline, I'm guessing it's not a huge leap forward to have them available to the public somewhere too. :) It can be a totally separate registry like `docker-preview.elastic.co` or something.

In the meantime, I'll follow your advice, thanks again.
