### ISSUE TITLE
Disable bootstrap checks

### ISSUE THREAD

**Issue by Puneeth-n** [elastic/elasticsearch-docker#138]
We use the official elasticsearch docker image (`docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.1`) for testing purposes on a build server. Is there a way to disable the bootstrap checks in elasticsearch?

**Comment by dliappis** [comment]
@Puneeth-n Bootstrap checks will not be active if you run the container in the "development-mode" as described here https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode , i.e. passing the parameter `-e "discovery.type=single-node"`.

**Comment by Puneeth-n** [comment]
yea eventually figured it out! Thanks!
