### ISSUE TITLE
Enable Docker content trust

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [elastic/elasticsearch-docker#158]
## Feature Description
Please enable [content trust](https://docs.docker.com/engine/security/trust/content_trust/) for all Docker images in docker.elastic.co.

Content trust allows clients to verify that Docker images are actually built by the distributor.

**Comment by rjernst** [comment]
I have opened https://github.com/elastic/elasticsearch/issues/43609. Maintenance of the docker files for elasticsearch has moved to the elasticsearch repo. As we will be archiving this repository, I am going to close this issue.
