### ISSUE TITLE
Install S3 repository plugin by default

### ISSUE THREAD

**Issue by ESamir** [elastic/elasticsearch-docker#16]
S3 repository plugin is very popular plugin used to snapshot the data , specially in the cloud 
I think it will be nice to have it installed  by default in the image

**Comment by jakommo** [comment]
Not sure this is the right approach. The image will also be used in self hosted environments or by users not using S3 and they should not be forced to have a plugin installed they never use. 
If someone needs a plugin, one can just modify the Dockerfile and add a line [like this](https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/Dockerfile#L31) and build it's own image

**Comment by jasontedor** [comment]
I agree with @jakommo, this should not be done.

**Comment by dliappis** [comment]
General consensus is not to include this, so I am going to close the issue.
