### ISSUE TITLE
 syntax error near unexpected token `<'

### ISSUE THREAD

**Issue by FengyunPan2** [elastic/elasticsearch-docker#161]
\# kubectl logs elasticsearch-logging-0  -n kube-system
\+ export NODE_NAME=elasticsearch-logging-0
\+ NODE_NAME=elasticsearch-logging-0
\+ export NODE_MASTER=true
\+ NODE_MASTER=true
\+ export NODE_DATA=true
\+ NODE_DATA=true
\+ export HTTP_PORT=9200
\+ HTTP_PORT=9200
\+ export TRANSPORT_PORT=9300
\+ TRANSPORT_PORT=9300
\+ export MINIMUM_MASTER_NODES=1
\+ MINIMUM_MASTER_NODES=1
\+ chown -R elasticsearch:elasticsearch /data
\+ ./bin/elasticsearch_logging_discovery
\+ exec su elasticsearch -c ./bin/es-docker
Killed

\# kubectl exec -it elasticsearch-logging-0 -n kube-system -- /bin/bash
[root@elasticsearch-logging-0 elasticsearch]# sh -x ./bin/es-docker
\+ declare -a es_opts
./bin/es-docker: line 23: syntax error near unexpected token `<'
./bin/es-docker: line 23: `done < <(env)'

**Comment by jarpy** [comment]
> `# sh -x ./bin/es-docker`

`es-docker` is a Bash script, but you're invoking it with a Bourne shell.

A standard Bourne shell can't understand some of the cool Bash features that `es-docker` employs.
