### ISSUE TITLE
Install plugins from env variable

### ISSUE THREAD

**Issue by LudovicTOURMAN** [elastic/elasticsearch-docker#164]
Actual ES docker images allow to define configuration through environment variable.
However, it is not possible to define plugins to be installed without any hack.

## Feature Description
ES docker images should provide a environment variable that would allow to set plugins to be installed.
I made a PR for this https://github.com/elastic/elasticsearch-docker/pull/162

This mechanic should be reported on all docker images.

**Comment by LudovicTOURMAN** [comment]
Hi Toby,

Even if I would like this option to be native in your docker images, I understand your point of view.

Thanks for your answer.

**Comment by jarpy** [comment]
Thank you, Ludovic, for being cool about it. ❤️
