### ISSUE TITLE
doc configuring tls docker not mentioning adding xpack license is needed from 6.3

### ISSUE THREAD

**Issue by jguay** [elastic/elasticsearch-docker#176]
## Bug Description
https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-tls-docker.html

Doc mentions image "elasticsearch-platinum:6.3.0"; I think this was corrected but there is one of those left at time of submitting this...

Also I'm not 100% sure of my testing because of the following issue which is already fixed in master /usr/local/bin/docker-entrypoint.sh, ELASTIC_PASSWORD does not update bootstrap.password to keystore in 6.3.0 so I have to add this and restart the container

This issue related to the fact the page currently does not mention anything related to adding an xpack license so authentication with basic authentication will not work so far as I understand as xpack would be disabled ?

## Feature Description

I think the doc needs a new point after point "2. Start two Elasticsearch nodes configured for SSL/TLS", it would be good to add:
"3. Activate [xpack trial license](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/start-trial.html) or [update your license](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/update-license.html)"

Optionally as I am not sure if we should provide a snippet, this is what I used : 
```
docker-compose exec es01 /bin/bash -c '
set -euo pipefail

es_url=https://localhost:9200

# Wait for Elasticsearch to start up before doing anything.
until curl -s $es_url -k -o /dev/null; do
    sleep 1
done

sleep 2

#start trial license
response=$(curl -k -s -H 'Content-Type:application/json' -XPOST $es_url/_xpack/license/start_trial?acknowledge=true)
while [[ "$response" = *"trial_was_started"* ]]
do
    sleep 2
    response=$(curl -k -s -H 'Content-Type:application/json' -XPOST $es_url/_xpack/license/start_trial?acknowledge=true)
done
'
```

**Comment by jarpy** [comment]
The docs have now been updated with the correct image name. They also now demonstrate setting up a self-generated trial licence in order to activate the security features.

Thanks for this great report!
