### ISSUE TITLE
[Feature Request] Support _FILE suffix in docker images

### ISSUE THREAD

**Issue by nikeee** [elastic/elasticsearch-docker#183]
## Feature Description
There is a convention on official docker images that environment variables that end in `_FILE` are read as a file and then assigned to a variable without the `_FILE` suffix. For example, setting the environment variable `ELASTIC_PASSWORD_FILE` to `/run/secrets/secret-password` will read the file `/run/secrets/secret-password` and assign its contents to the environment variable `ELASTIC_PASSWORD`. This is especially handy when using Docker secrets.

Related issue on Grafana: https://github.com/grafana/grafana-docker/pull/166
Thread on forums: https://discuss.elastic.co/t/feature-request-support-file-suffix-in-docker-images/140107

**Comment by rjernst** [comment]
Maintenance of the docker files for elasticsearch has moved to the [elasticsearch repo](https://github.com/elastic/elasticsearch). As we will be archiving this repository, I am going to close this issue and I have migrated it to https://github.com/elastic/elasticsearch/issues/43603.
