### ISSUE TITLE
standard_init_linux.go:178: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by InspurKelly** [elastic/elasticsearch-docker#191]
HI，
I modified docker-entrypoint.sh  and Dockerfile，

Dockerfile：
FROM docker.elastic.co/elasticsearch/elasticsearch:6.3.2
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

when run images，an error occurred：
standard_init_linux.go:178: exec user process caused "no such file or directory"

Can you help me solve it? Thanks

**Comment by InspurKelly** [comment]
I solved it，beacuse docker-entrypoint.sh contains ^M, thanks.

**Comment by jarpy** [comment]
No problem. I'm glad you found it. It's a hard problem to see (since it's invisible!).
