### ISSUE TITLE
Impossible to download es-basic:6.3

### ISSUE THREAD

**Issue by Nek-** [elastic/elasticsearch-docker#193]
## Bug Description

Impossible to pull es-basic:6.3.x

```
$ docker pull docker.elastic.co/elasticsearch/elasticsearch-basic:6.3.2
Error response from daemon: manifest for docker.elastic.co/elasticsearch/elasticsearch-basic:6.3.2 not found
```

**Comment by xeraa** [comment]
Thanks for reporting — you are correct. That image does not exist. With the merging of X-Pack in 6.3.0 there are now only 2 packages any more:

* The default one, which includes X-Pack and has the basic license enabled by default; you can start a trial once per major version.
* The open source version.

Did you get that information from https://www.docker.elastic.co or somewhere else? To get the 6.3.x packages follow the same pattern as 6.4.0. So `docker pull docker.elastic.co/elasticsearch/elasticsearch:6.3.2` should get you what you want.

@karmi I think we need to update https://www.docker.elastic.co. 6.4.0 has the right images, but 6.3.x uses the wrong schema from 6.2.x and earlier.

**Comment by Nek-** [comment]
Yes this information was from https://www.docker.elastic.co/ indeed. I though it was only merged with 6.3.x releases. My bad! An update of the website would be great indeed.

**Comment by karmi** [comment]
Hi @Nek-, thanks for the report!, that's indeed a bug on the website.

@xeraa , I'd like to transfer it to @fxdgear , who's the main owner of the Docker infrastructure now.

**Comment by jarpy** [comment]
Is this something you are OK to look at now, @fxdgear?

**Comment by fxdgear** [comment]
Catching up on old tickets I've been tagged in. 

Yes I'll look into this. right now getting Clients-CI up and running is priority number 1 but I'll take a look at this asap
