### ISSUE TITLE
make UID/GID configurable

### ISSUE THREAD

**Issue by tclh123** [elastic/elasticsearch-docker#194]
The UID/GID is hardcoded to 1000, it should be configurable.

**Comment by jarpy** [comment]
Hi,

The UID is configurable now through the standard mechanism eg. `docker run --uid`. The primary GID is always 1000, but the user is also a member of GID 0, in accordance with the [OpenShift guidelines](https://docs.openshift.com/container-platform/3.5/creating_images/guidelines.html) for building images that can support arbitrary UIDs. This image complies with those guidlines and [can run with arbitrary UIDs](https://github.com/elastic/elasticsearch-docker/blob/64053299b7f4aca16b7e381937fd7a53b4689a46/tests/test_datadirs.py#L17).

If it's not working, please let us know.

**Comment by tclh123** [comment]
Hello @jarpy , it works, thanks.

By the way, I think the option is `-u/--user` not `--uid`, and we should pass the UID of the user to this option not username. Like,

```
docker run -u "$(id -u elasticsearch)" ...
```
