### ISSUE TITLE
Support webhooks which trigger on image updates

### ISSUE THREAD

**Issue by nphmuller** [elastic/elasticsearch-docker#199]
## Feature Description
We use webhooks on Docker hub to rebuild our images when a baseimage is updated. It would be great if this could also be accomplished with the elasticsearch docker images.

**Comment by xeraa** [comment]
I guess https://hub.docker.com/r/elastic/elasticsearch/ will work for you, right? It's mirroring our own Docker repository in case you need Docker Hub for some reason (webhooks might be one of them).

**Comment by nphmuller** [comment]
Didn't know that one existed. Only knew about https://hub.docker.com/_/elasticsearch/ which has a deprecation notice.

Thanks!
