### ISSUE TITLE
Dockerfile for Elasticsearch

### ISSUE THREAD

**Issue by robel-yemane** [elastic/elasticsearch-docker#216]
Hiya,
I (my team) have a requirement to convert ELK in K8s, but I can't use the image provided from https://www.docker.elastic.co/ as it uses centos as a base image, and for licensing reasons we cannot use that. 
So I am planning to create a dockerfile for Elasticsearch based on Debian or other images, and for that I'd need to see the source Dockerfile used by ES, but I can't find it anywhere.
Your help is appreciated.

**Comment by xeraa** [comment]
I assume you're after https://github.com/elastic/elasticsearch-docker/blob/master/templates/Dockerfile.j2? We're using some additional Python magic for making builds and tests easier (or even possible).

**Comment by robel-yemane** [comment]
Right can I use that on Dockerfile (not in Jinja template format?) ?

**Comment by xeraa** [comment]
Well, if you want to use a plain Dockerfile you will need to strip out all the Jinja parts — `{%`.

**Comment by robel-yemane** [comment]
Yep, I guess I'll do that. Thanks.
One more thing, I found the below, but not sure if it was official ES config
https://github.com/docker-library/elasticsearch/blob/7d09a4ec10b02fa8ec5d396436209e4ab885aa87/Dockerfile-alpine.template

**Comment by xeraa** [comment]
That's from Docker Inc. If I remember correctly it changes permissions on the bind mounted folders, which we don't think is a good idea.
