### ISSUE TITLE
CLI command runs out of memory

### ISSUE THREAD

**Issue by eliecharra** [elastic/elasticsearch-docker#219]
* Docker image used

`docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.1`

* Operating System

```
Linux es1 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64 GNU/Linux
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch
```

* `docker info` output
```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-7-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.34GiB
Name: es1.clnk.fr
ID: OQV4:ZE2L:DLEU:GEJC:XZGD:NMY7:4W7R:44IX:CPCQ:IVUC:CXXS:MXR3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true

WARNING: No swap limit support
```

* Steps to reproduce
--> Run a docker container allocating 90% of the host memory to java heap `ES_JAVA_OPTS=-Xms12G -Xmx12G`
--> Run docker `docker exec elasticsearch bin/elasticsearch-keystore list`
--> Failure :

```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000500000000, 12884901888, 0) failed; error='Not enough space' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 12884901888 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /usr/share/elasticsearch/hs_err_pid426.log
```

## Bug Description

Setting java heap limits with environment variable makes all CLI command to fail as they try to allocate a large heap too. This behavior is a little bit confusing IMHO.

Maybe we should recommend setting heap size in a [different way](https://www.elastic.co/guide/en/elasticsearch/reference/current/jvm-options.html) in the documentation.
Workaround is quite easy, override ES_JAVA_OPTS in docker exec : `docker exec -e ES_JAVA_OPTS= elasticsearch bin/elasticsearch-keystore list`
This bug is not critical at all but I spend hours looking for memory issues in my docker setup, maybe this issue could help people, and maybe we could update doc to warn about it ...

**Comment by xeraa** [comment]
Sidenote: Maybe we should document the priority of the options better, since this is probably not intuitive.

**Comment by gentunian** [comment]
@eliecharra I think it should be safe to do something like this:

```
docker exec -it -e ES_JAVA_OPTS="-Xmx512m -Xms512m" <container-id> bin/elasticsearch-keystore add xpack.notification.slack.account.monitoring.secure_url
```

**Comment by rjernst** [comment]
This is a [known issue](https://github.com/elastic/elasticsearch/issues/42021) in Elasticsearch, and unrelated to docker.

Additionally, maintenance of the docker files for elasticsearch has moved to the elasticsearch repo. Please open any future issues with docker there. As this this repository will be archived, I am closing this issue.
