### ISSUE TITLE
Elastic docker fails to start when running with windows containers + experimental on

### ISSUE THREAD

**Issue by ronyf** [elastic/elasticsearch-docker#228]
I'm running Docker on Windows 10.
I've set docker to run with Windows containers and ticked "Experimental features" under Daemon to be able to run both linux and windows containers on my environment.

My `docker-compose` file is set like so:

	version: '2.4'
	services:
	  ...
	  elasticsearch:
		image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
		container_name: elasticsearch
		ports:
		  - 9200:9200
		  - 9300:9300
		environment:
		  - cluster.name=elasticsearch
		  - bootstrap.memory_lock=false
		  - path.repo=/usr/share/elasticsearch/repo
		  - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
		volumes:
		  - C:\tmp\data:/usr/share/elasticsearch/data
		  - C:\tmp\repo:/usr/share/elasticsearch/repo
		platform: centos
	  ...

and when I run it, I get the following error:

	elasticsearch    | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
	elasticsearch    | [2018-12-30T08:22:58,027][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [unknown] uncaught exception in thread [main]
	elasticsearch    | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.5.4.jar:6.5.4]
	elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.5.4.jar:6.5.4]
	elasticsearch    |      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.5.4.jar:6.5.4]
	elasticsearch    |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.5.4.jar:6.5.4]
	elasticsearch    |      at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.5.4.jar:6.5.4]
	elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.5.4.jar:6.5.4]
	elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.5.4.jar:6.5.4]
	elasticsearch    | Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?

`docker info` output:

	Containers: 3
	 Running: 1
	 Paused: 0
	 Stopped: 2
	Images: 4
	Server Version: 18.09.0
	Storage Driver: windowsfilter (windows) lcow (linux)
	 Windows:
	 LCOW:
	Logging Driver: json-file
	Plugins:
	 Volume: local
	 Network: ics l2bridge l2tunnel nat null overlay transparent
	 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
	Swarm: inactive
	Default Isolation: hyperv
	Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
	Operating System: Windows 10 Pro Version 1803 (OS Build 17134.472)
	OSType: windows
	Architecture: x86_64
	CPUs: 4
	Total Memory: 15.67GiB
	Name: gc-pc-055
	ID: CZVV:AW3A:VN54:4GWS:IRL6:QB2S:VYYK:VDU2:5GSP:3HHB:PTSI:Y3T7
	Docker Root Dir: C:\ProgramData\Docker
	Debug Mode (client): false
	Debug Mode (server): true
	 File Descriptors: -1
	 Goroutines: 45
	 System Time: 2018-12-30T10:24:36.8089366+02:00
	 EventsListeners: 1
	Registry: https://index.docker.io/v1/
	Labels:
	Experimental: true
	Insecure Registries:
	 127.0.0.0/8
	Live Restore Enabled: false
	Product License: Community Engine

`docker inspect` output:

	[
		{
			"Id": "dbc02f2b2dab828e67413ada98b822d027e8b0c10dfb0366a057bc508bc03df9",
			"Created": "2018-12-30T08:22:45.6898111Z",
			"Path": "/usr/local/bin/docker-entrypoint.sh",
			"Args": [
				"eswrapper"
			],
			"State": {
				"Status": "exited",
				"Running": false,
				"Paused": false,
				"Restarting": false,
				"OOMKilled": false,
				"Dead": false,
				"Pid": 0,
				"ExitCode": 1,
				"Error": "",
				"StartedAt": "2018-12-30T08:22:49.8147598Z",
				"FinishedAt": "2018-12-30T10:22:58.9909388+02:00"
			},
			"Image": "sha256:93109ce1d590482a06ba085943082b314ac188fcfdbffb68aebb00795c72bc8a",
			"ResolvConfPath": "",
			"HostnamePath": "",
			"HostsPath": "",
			"LogPath": "C:\\ProgramData\\Docker\\containers\\dbc02f2b2dab828e67413ada98b822d027e8b0c10dfb0366a057bc508bc03df9\\dbc02f2b2dab828e67413ada98b822d027e8b0c10dfb0366a057bc508bc03df9-json.log",
			"Name": "/elasticsearch",
			"RestartCount": 0,
			"Driver": "lcow",
			"Platform": "linux",
			"MountLabel": "",
			"ProcessLabel": "",
			"AppArmorProfile": "",
			"ExecIDs": null,
			"HostConfig": {
				"Binds": [
					"C:\\tmp\\elasticsearch\\data:/usr/share/elasticsearch/data:rw",
					"C:\\tmp\\elasticsearch\\repo:/usr/share/elasticsearch/repo:rw"
				],
				"ContainerIDFile": "",
				"LogConfig": {
					"Type": "json-file",
					"Config": {}
				},
				"NetworkMode": "local_management_default",
				"PortBindings": {
					"9200/tcp": [
						{
							"HostIp": "",
							"HostPort": "9200"
						}
					],
					"9300/tcp": [
						{
							"HostIp": "",
							"HostPort": "9300"
						}
					]
				},
				"RestartPolicy": {
					"Name": "",
					"MaximumRetryCount": 0
				},
				"AutoRemove": false,
				"VolumeDriver": "",
				"VolumesFrom": [],
				"CapAdd": null,
				"CapDrop": null,
				"Dns": null,
				"DnsOptions": null,
				"DnsSearch": null,
				"ExtraHosts": null,
				"GroupAdd": null,
				"IpcMode": "",
				"Cgroup": "",
				"Links": null,
				"OomScoreAdj": 0,
				"PidMode": "",
				"Privileged": false,
				"PublishAllPorts": false,
				"ReadonlyRootfs": false,
				"SecurityOpt": null,
				"UTSMode": "",
				"UsernsMode": "",
				"ShmSize": 0,
				"ConsoleSize": [
					0,
					0
				],
				"Isolation": "hyperv",
				"CpuShares": 0,
				"Memory": 0,
				"NanoCpus": 0,
				"CgroupParent": "",
				"BlkioWeight": 0,
				"BlkioWeightDevice": null,
				"BlkioDeviceReadBps": null,
				"BlkioDeviceWriteBps": null,
				"BlkioDeviceReadIOps": null,
				"BlkioDeviceWriteIOps": null,
				"CpuPeriod": 0,
				"CpuQuota": 0,
				"CpuRealtimePeriod": 0,
				"CpuRealtimeRuntime": 0,
				"CpusetCpus": "",
				"CpusetMems": "",
				"Devices": null,
				"DeviceCgroupRules": null,
				"DiskQuota": 0,
				"KernelMemory": 0,
				"MemoryReservation": 0,
				"MemorySwap": 0,
				"MemorySwappiness": null,
				"OomKillDisable": null,
				"PidsLimit": 0,
				"Ulimits": null,
				"CpuCount": 0,
				"CpuPercent": 0,
				"IOMaximumIOps": 0,
				"IOMaximumBandwidth": 0,
				"MaskedPaths": null,
				"ReadonlyPaths": null
			},
			"GraphDriver": {
				"Data": {
					"dir": "C:\\ProgramData\\Docker\\lcow\\dbc02f2b2dab828e67413ada98b822d027e8b0c10dfb0366a057bc508bc03df9"
				},
				"Name": "lcow"
			},
			"Mounts": [
				{
					"Type": "bind",
					"Source": "c:\\tmp\\elasticsearch\\data",
					"Destination": "/usr/share/elasticsearch/data",
					"Mode": "",
					"RW": true,
					"Propagation": ""
				},
				{
					"Type": "bind",
					"Source": "c:\\tmp\\elasticsearch\\repo",
					"Destination": "/usr/share/elasticsearch/repo",
					"Mode": "",
					"RW": true,
					"Propagation": ""
				}
			],
			"Config": {
				"Hostname": "dbc02f2b2dab",
				"Domainname": "",
				"User": "",
				"AttachStdin": false,
				"AttachStdout": false,
				"AttachStderr": false,
				"ExposedPorts": {
					"9200/tcp": {},
					"9300/tcp": {}
				},
				"Tty": false,
				"OpenStdin": false,
				"StdinOnce": false,
				"Env": [
					"cluster.name=elasticsearch",
					"bootstrap.memory_lock=false",
					"path.repo=/usr/share/elasticsearch/repo",
					"ES_JAVA_OPTS=-Xms512m -Xmx512m",
					"PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
					"ELASTIC_CONTAINER=true",
					"JAVA_HOME=/opt/jdk-11.0.1"
				],
				"Cmd": [
					"eswrapper"
				],
				"ArgsEscaped": true,
				"Image": "docker.elastic.co/elasticsearch/elasticsearch:6.5.4",
				"Volumes": {
					"/usr/share/elasticsearch/data": {},
					"/usr/share/elasticsearch/repo": {}
				},
				"WorkingDir": "/usr/share/elasticsearch",
				"Entrypoint": [
					"/usr/local/bin/docker-entrypoint.sh"
				],
				"OnBuild": null,
				"Labels": {
					"com.docker.compose.config-hash": "06ca83baa0c030528415db4283e331f522dff1245b682e7c30f1580d52715be6",
					"com.docker.compose.container-number": "1",
					"com.docker.compose.oneoff": "False",
					"com.docker.compose.project": "local_management",
					"com.docker.compose.service": "elasticsearch",
					"com.docker.compose.version": "1.23.2",
					"license": "Elastic License",
					"org.label-schema.build-date": "20181205",
					"org.label-schema.license": "GPLv2",
					"org.label-schema.name": "elasticsearch",
					"org.label-schema.schema-version": "1.0",
					"org.label-schema.url": "https://www.elastic.co/products/elasticsearch",
					"org.label-schema.vcs-url": "https://github.com/elastic/elasticsearch-docker",
					"org.label-schema.vendor": "Elastic",
					"org.label-schema.version": "6.5.4"
				}
			},
			"NetworkSettings": {
				"Bridge": "",
				"SandboxID": "dbc02f2b2dab828e67413ada98b822d027e8b0c10dfb0366a057bc508bc03df9",
				"HairpinMode": false,
				"LinkLocalIPv6Address": "",
				"LinkLocalIPv6PrefixLen": 0,
				"Ports": {},
				"SandboxKey": "dbc02f2b2dab828e67413ada98b822d027e8b0c10dfb0366a057bc508bc03df9",
				"SecondaryIPAddresses": null,
				"SecondaryIPv6Addresses": null,
				"EndpointID": "",
				"Gateway": "",
				"GlobalIPv6Address": "",
				"GlobalIPv6PrefixLen": 0,
				"IPAddress": "",
				"IPPrefixLen": 0,
				"IPv6Gateway": "",
				"MacAddress": "",
				"Networks": {
					"local_management_default": {
						"IPAMConfig": null,
						"Links": null,
						"Aliases": [
							"dbc02f2b2dab",
							"elasticsearch"
						],
						"NetworkID": "7bcf0bd8aa6bac42720f0c31125232dc0e57bf09b64c33a56d6c93beb82345de",
						"EndpointID": "",
						"Gateway": "",
						"IPAddress": "",
						"IPPrefixLen": 0,
						"IPv6Gateway": "",
						"GlobalIPv6Address": "",
						"GlobalIPv6PrefixLen": 0,
						"MacAddress": "",
						"DriverOpts": null
					}
				}
			}
		}
	]

`docker-compose`  version:

    docker-compose version 1.23.2, build 1110ad01

**Comment by xeraa** [comment]
Just to be sure: Did you set up the correct permissions for the bind mounted folders? And if yes, does it work without the experimental flag?

See our docs for the right permissions on the bind mounted directory: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_b_bind_mounted_configuration

**Comment by xeraa** [comment]
That sounds like an interesting bug then 😅 

Unfortunately I don't have any Windows installations handy at the moment, so I hope somebody else on the team can dive into this...

**Comment by rjernst** [comment]
At this time we do not support running in a Windows container. Additionally, maintenance of the docker files for elasticsearch have moved to the [elasticsearch repo](https://github.com/elastic/elasticsearch). Please open any future issues with docker there. As this this repository will be archived, I am closing this issue.
