### ISSUE TITLE
Error when running docker-compose

### ISSUE THREAD

**Issue by shavo007** [elastic/elasticsearch-docker#4]
Hi,

I tried to run docker compose based on the file attached here:
https://gist.githubusercontent.com/dliappis/52de1f4bb10fd23f5b91ea5fcb5d2560/raw/260723cf8d496ed15a5dd4801a6e9cb616c9f3c3/docker-compose.yml

Error Im getting is:

`Pulling elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:latest)...
ERROR: Get https://docker.elastic.co/v2/elasticsearch/elasticsearch/manifests/latest: Get https://container-registry.elastic.co:7000/auth?scope=repository%3Aelasticsearch%2Felasticsearch%3Apull&service=token-service: EOF
`

Versions:
Docker version 1.12.1, build 6f9534c, experimental
docker-compose version 1.8.0, build f3628c7

**Comment by dliappis** [comment]
@shavo007 Thanks for testing the images!

I couldn't reproduce that, but what is the operating system you are running docker + docker-compose on?

1. Does the issue still persist?
2. Would it be possible to try using [docker-engine stable](https://docs.docker.com/engine/installation/) 1.12.1 as opposed to an experimental version?
3. Do you happen to be behind a firewall/proxy that blocks outgoing access to port 7000?

**Comment by shavo007** [comment]
All good!

I ran it at home and worked perfectly. 

Looks like it must be a firewall issue in work. 

Thanks.

**Comment by dliappis** [comment]
@shavo007 Awesome, thanks again for your interest!

**Comment by mcesar** [comment]
My corporate firewall blocks all ports except 80 and 443. Is there any workaround?

**Comment by dliappis** [comment]
@mcesar Unfortunately not at the moment from the side of the Elastic docker registry. One workaround, if you have access to a registry of your own, you can create [a customized image](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_c_customized_image) and push to that instead.

Will post an update if there is a change in the port requirements.

**Comment by owenbutler** [comment]
@dliappis I'd like to add another data point to the problem of being blocked by corporate/whatever firewalls.  I'm unable to access port 7000.  Most of the rest of the docker ecosystem (hub, etc) work fine.

Is it possible to move/change the custom elasticsearch register off 7000 on to 443?

**Comment by dliappis** [comment]
@owenbutler Thanks for your feedback! For the record the registry itself is listening on 443 but there is an additional auth component that runs on a separate port. Moving that to 443 too is on our radar and will be working on a change, but, at this point can not confirm a specific date. Will let you know when that's been done.

**Comment by owenbutler** [comment]
Thanks for the update @dliappis 👍

**Comment by ifourmanov** [comment]
I'm affected here as well, as are many corporate users around the globe. Effectively elastic.co docker distribution is unusable.
Given that it's a public registry hosting official images I don't even understand why you need an authentication endpoint for pulls. Moving that endpoint port to 443 would solve the issue.
Until then, is it possible to provide mirror of official elastic docker images on hub.docker.com, which doesn't have such issues?

**Comment by dliappis** [comment]
@ifourmanov Thank you for the feedback and apologies for the inconvenience. The auth step is something done by most registries, I believe also in [docker hub](https://docs.docker.com/registry/spec/auth/jwt/) and is needed as there are some private artifacts. The diff here is that the auth component listens on port 7000.

This is a high priority item, so we'll be addressing this shortly.

**Comment by seankellner** [comment]
Also impacted by not being able to hit port 7000. Customized image is not an option due to following your docs leads to "FROM docker.elastic.co/elasticsearch/elasticsearch:5.2.2" which does the same pull with the same port 7000 restriction. If I could find your Dockerfile (and possibly a chain of them back to a publicly available FROM line) I could do a custom build.

**Comment by dliappis** [comment]
You should now be able to pull images from `docker.elastic.co` in restricted environments that only allow outgoing connections to port 443. Thank you for your patience!

**Comment by owenbutler** [comment]
Thanks @dliappis !
