### ISSUE TITLE
delete_by_query doesn't obey `wait_for_completion`

### ISSUE THREAD

**Issue by ParthGandhi** [elastic/elasticsearch-docker#41]
I don't know if this is a docker problem or a general ES bug, but it looks like when I run the container locally and run a `delete_by_query`, it doesn't wait for it to complete if I add the parameter `wait_for_completion=True`

This also happens for the tasks API.

Happy to give a workable test if you'd like, but was just wondering if this was a known bug off the top of your head.

**Comment by xeraa** [comment]
What's the reason that you assume this doesn't work?

I've just tried it with our Elasticsearch + Kibana images. Here are query and result for waiting:

```
POST twitter/_delete_by_query?wait_for_completion=true
{
  "query": { 
    "match": {
      "user": "foo"
    }
  }
}

{
  "took": 148,
  "timed_out": false,
  "total": 3,
  "deleted": 3,
  "batches": 1,
  "version_conflicts": 0,
  "noops": 0,
  "retries": {
    "bulk": 0,
    "search": 0
  },
  "throttled_millis": 0,
  "requests_per_second": -1,
  "throttled_until_millis": 0,
  "failures": []
}
```

And here is the result without waiting — notice the task you're getting back:

```
POST twitter/_delete_by_query?wait_for_completion=false
{
  "query": { 
    "match": {
      "user": "foo"
    }
  }
}

{
  "task": "IqmgBvLrRWS5BSsdA8RKSg:801756"
}
```

Maybe you had a capital F on the `False`? `POST twitter/_delete_by_query?wait_for_completion=False` behaves like `POST twitter/_delete_by_query?wait_for_completion=true`
