### ISSUE TITLE
Support for Elasticsearch versions other than 5.x

### ISSUE THREAD

**Issue by bploetz** [elastic/elasticsearch-docker#42]
## Feature Description

For those of us that can't upgrade to ES 5.x (yet), it would be super helpful if there was an official 2.X version of this Docker image that we could build upon. Any plans to support versions prior to 5.x?

**Comment by jarpy** [comment]
I have to be honest and say there's no plans, sorry.

I don't imagine the basic image would be that hard to create, but we demand (of ourselves), full documentation, acceptance tests and release automation. The total body work to release 2.x images at a standard that we'd be happy with is out of scope.
