### ISSUE TITLE
executable file not found in $PATH

### ISSUE THREAD

**Issue by plemarquand** [elastic/elasticsearch-docker#45]
* `docker info` output:
```
Containers: 13
 Running: 0
 Paused: 0
 Stopped: 13
Images: 117
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.71 GiB
Name: moby
ID: FX7I:NJNA:YJZN:LC7Z:6XA4:XGEJ:HUO5:MC24:FTIQ:D2WM:H3LZ:56Z6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2017-03-29T18:26:49.377743743Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
* `docker-compose` version:
docker-compose version 1.11.2, build dfed245

* Host OS and version:
MacOS 10.10.5 

## Bug description

ElasticSearch containers pulled from docker.elastic.co fail to start and throw the following error: `docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"-Etransport.host=0.0.0.0\": executable file not found in $PATH".` I've tried all the 5.x variants of the image and all exhibit the same problem.

Here is the command used: `docker run -d -p 9118:9200 -p 9119:9300 --name tester_es docker.elastic.co/elasticsearch/elasticsearch:5.3.0 -Etransport.host=0.0.0.0 -Ehttp.host=0.0.0.0`

Interestingly, containers pulled from the soon-to-be-deprecated docker hub collection start up and run just fine: `docker run -d -p 9118:9200 -p 9119:9300 --name tester_es elasticsearch:5.3.0 -Etransport.host=0.0.0.0 -Ehttp.host=0.0.0.0`

**Comment by dliappis** [comment]
The ES parameters need to be passed as docker environment variables, see the [example here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode).

The image on Docker Hub uses `-E` style cli parameters for the elasticsearch process.
The Elastic maintained image requires ES parameters to be passed as env vars instead, for example:

```bash
docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.3.0
```

**Comment by plemarquand** [comment]
@dliappis That did the trick! Thanks for the quick response. I ran into this when porting from docker hub so hopefully your explanation helps others when they do the same.
