### ISSUE TITLE
Exception in thread "main" java.nio.file.AccessDeniedException: /tmp/6291781730439625928.zip

### ISSUE THREAD

**Issue by svanschalkwyk** [elastic/elasticsearch-docker#47]
$make

Step 12/20 : RUN eval ${ES_JAVA_OPTS:-} elasticsearch-plugin install --batch x-pack
 ---> Running in 07d8088bc9ee
-> Downloading x-pack from elastic
Exception in thread "main" java.nio.file.AccessDeniedException: /tmp/6291781730439625928.zip
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)

Kernel Version: 4.4.0-62-generic
Operating System: Linux Mint 18

$ docker info
Containers: 36
 Running: 0
 Paused: 0
 Stopped: 36
Images: 331
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 316
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Linux Mint 18
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.3 GiB
Name: swartjie
ID: OBAE:PF6U:XIE3:IOVE:H7LT:RFXR:YJMI:2DXA:KIF5:DV4K:IOLY:I6VR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by jarpy** [comment]
That's super strange. It's precisely the kind of thing that Docker should make identical across different systems.

It would be interesting to see inside the image produced in step 11. I would need a couple more lines on the top of your log to give you and exact command, but locally I got this:

```
Step 11/20 : USER elasticsearch
 ---> Running in a70ea1cb8047
 ---> d1bae721c16b
```

So I now have layer 11 with ID `d1bae721c16b`, which I can investigate like this:

```
$ docker run --rm -it d1bae721c16b bash
bash-4.3$ stat /tmp
  File: /tmp
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 66h/102d        Inode: 45          Links: 2
Access: (1777/drwxrwxrwt)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-02-17 15:11:39.000000000
Modify: 2016-10-18 18:58:04.000000000
Change: 2017-02-15 11:36:14.000000000

bash-4.3$ df -h
Filesystem                Size      Used Available Use% Mounted on
none                    870.0G    176.9G    648.8G  21% /
tmpfs                   125.9G         0    125.9G   0% /dev
tmpfs                   125.9G         0    125.9G   0% /sys/fs/cgroup
/dev/mapper/vg00-root
                        870.0G    176.9G    648.8G  21% /etc/resolv.conf
/dev/mapper/vg00-root
                        870.0G    176.9G    648.8G  21% /etc/hostname
/dev/mapper/vg00-root
                        870.0G    176.9G    648.8G  21% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   125.9G         0    125.9G   0% /proc/kcore
tmpfs                   125.9G         0    125.9G   0% /proc/timer_list
tmpfs                   125.9G         0    125.9G   0% /proc/timer_stats
tmpfs                   125.9G         0    125.9G   0% /proc/sched_debug
tmpfs                   125.9G         0    125.9G   0% /sys/firmware

bash-4.3$ whoami
elasticsearch
```

**Comment by svanschalkwyk** [comment]
Example 1:
`make run-es-single 
docker pull docker.elastic.co/elasticsearch/elasticsearch-alpine-base:latest
latest: Pulling from elasticsearch/elasticsearch-alpine-base
Digest: sha256:7d90d00e57ddd752b2827205eb035b64cde294c7bbf671a21dc8e3f23ac00cff
Status: Image is up to date for docker.elastic.co/elasticsearch/elasticsearch-alpine-base:latest
ES_NODE_COUNT=1 docker-compose -f docker-compose.yml -f docker-compose.hostports.yml up --build elasticsearch1
Building elasticsearch1
Step 1/20 : FROM docker.elastic.co/elasticsearch/elasticsearch-alpine-base:latest
 ---> 47f4aed2574c
Step 2/20 : MAINTAINER Elastic Docker Team <docker@elastic.co>
 ---> Using cache
 ---> cd84fc03fedd
Step 3/20 : ARG ELASTIC_VERSION
 ---> Using cache
 ---> d60299951f93
Step 4/20 : ARG ES_DOWNLOAD_URL
 ---> Using cache
 ---> d244f7f0e867
Step 5/20 : ARG ES_JAVA_OPTS
 ---> Using cache
 ---> b2847e518e75
Step 6/20 : ENV PATH /usr/share/elasticsearch/bin:$PATH
 ---> Using cache
 ---> d3965bcfd492
Step 7/20 : ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
 ---> Using cache
 ---> 6e495d53fd1a
Step 8/20 : WORKDIR /usr/share/elasticsearch
 ---> Using cache
 ---> b96a865fb317
Step 9/20 : RUN wget ${ES_DOWNLOAD_URL}/elasticsearch-${ELASTIC_VERSION}.tar.gz &&     EXPECTED_SHA=$(wget -O - ${ES_DOWNLOAD_URL}/elasticsearch-${ELASTIC_VERSION}.tar.gz.sha1) &&     test $EXPECTED_SHA == $(sha1sum elasticsearch-${ELASTIC_VERSION}.tar.gz | awk '{print $1}') &&     tar zxf elasticsearch-${ELASTIC_VERSION}.tar.gz &&     chown -R elasticsearch:elasticsearch elasticsearch-${ELASTIC_VERSION} &&     mv elasticsearch-${ELASTIC_VERSION}/* . &&     rmdir elasticsearch-${ELASTIC_VERSION} &&     rm elasticsearch-${ELASTIC_VERSION}.tar.gz
 ---> Using cache
 ---> 2176267b30b5
Step 10/20 : RUN set -ex && for esdirs in config data logs; do         mkdir -p "$esdirs";         chown -R elasticsearch:elasticsearch "$esdirs";     done
 ---> Using cache
 ---> 033dd3286f68
Step 11/20 : USER elasticsearch
 ---> Using cache
 ---> 29cb28e2ff9c
Step 12/20 : RUN eval ${ES_JAVA_OPTS:-} elasticsearch-plugin install --batch x-pack
 ---> Running in 05bde204a477
-> Downloading x-pack from elastic
Exception in thread "main" java.nio.file.AccessDeniedException: /tmp/3203638468915898709.zip
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
	at java.nio.file.Files.createTempFile(Files.java:852)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:271)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZipAndChecksum(InstallPluginCommand.java:318)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:227)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:206)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:192)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
ERROR: Service 'elasticsearch1' failed to build: The command '/bin/sh -c eval ${ES_JAVA_OPTS:-} elasticsearch-plugin install --batch x-pack' returned a non-zero code: 1
Makefile:39: recipe for target 'run-es-single' failed
make: *** [run-es-single] Error 1
`

**Comment by svanschalkwyk** [comment]
One elasticsearch-docker container from 11/26/2016 seemed to have been the culprit. Cleaned out my images and the problem is solved.
Sorry to have wasted your time!

**Comment by dliappis** [comment]
Glad you got it sorted out!
