### ISSUE TITLE
LDAP/AD Authentication and custom role mapping

### ISSUE THREAD

**Issue by Madhu1512** [elastic/elasticsearch-docker#5]
How do we enable LDAP/AD authentication for shield and add custom role mapping?

**Comment by dliappis** [comment]
To configure AD for x-pack security please have a look at: https://www.elastic.co/guide/en/x-pack/current/active-directory-realm.html. The corresponding documentation for LDAP can be found under: https://www.elastic.co/guide/en/x-pack/current/ldap-realm.html. Please note that shield is now called x-pack security, post 5.0.0.

If you don't want to build your own image based on the Dockerfile, you can create a [custom elasticsearch.yml](https://www.elastic.co/guide/en/x-pack/current/active-directory-realm.html#_configuring_an_active_directory_realm) as well as your custom role mapping file ([role_mapping.yml](https://www.elastic.co/guide/en/x-pack/current/mapping-roles.html)) and map those inside the container using [a volume bind mount](https://docs.docker.com/engine/reference/run/#/volume-shared-filesystems). So you'd need to create and distribute your `role_mapping.yml` and `elasticsearch.yml` file on the hosts and mount those inside the containers using `-v <path_to_yml_files>/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml` and `-v <path_to_yml_files>/role_mapping.yml:/usr/share/elasticsearch/config/x-pack/role_mapping.yml` -- you'll need to check the documentation of your docker orchestration framework on how to do volume mounts.

Depending on how static your configuration is, you may wish to use the [Dockerfile](https://github.com/elastic/elasticsearch-docker/blob/5.0/build/elasticsearch/Dockerfile#L33) as a basis, build your own images and bake in your own `elasticsearch.yml` and `role_mapping.yml` files with COPY commands -- just make sure they end up in the right directory under `/usr/share/elasticsearch/config` after as shown above.

Hope that helps!

**Comment by dliappis** [comment]
Closing to keep things tidy. Please re-open if you need any more help.
