### ISSUE TITLE
Exposing 127.0.0.1/localhost by default for testing elastic on GitLab CI

### ISSUE THREAD

**Issue by barseghyanartur** [elastic/elasticsearch-docker#52]
I want to use Docker for testing the elastic on GitLab CI.

In the example [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) it's stated that the following command could be used:

```shell
docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.3.0
```

However, if I just run the following it binds elastic to a random address.

```shell
docker run docker.elastic.co/elasticsearch/elasticsearch:5.3.0
```

I need to have it set to 127.0.0.1:9200 by default (with no arguments provided).

Changing yml file to the following did not help:

```text
network.host: 0.0.0.0
http.port: 9200
http.cors.enabled: true
http.cors.allow-origin: "/.*/"
http.host: 0.0.0.0
transport.host: 127.0.0.1
```

I also tried other settings such as:

```text
network.publish_host: 127.0.0.1
network.bind_host: 127.0.0.1
```

All attempts failed. Any advice on this?

**Comment by dliappis** [comment]
@barseghyanartur The Docker images ships with a very simple [elasticsearch.yml](https://github.com/elastic/elasticsearch-docker/blob/5.3/build/elasticsearch/elasticsearch.yml) that doesn't alter the defaults for the port that Elasticsearch binds to, which is `9200` and `9300` **inside the container**.
The [Dockerfile](https://github.com/elastic/elasticsearch-docker/blob/5.3/build/elasticsearch/Dockerfile#L44) used for building the image, exposes port `9200` and `9300`, however [publishing](https://docs.docker.com/engine/reference/builder/#expose) i.e. making ports accessible to the host is something you need to do with docker engine. With `docker run` 

So, the command you are using (`docker run docker.elastic.co/elasticsearch/elasticsearch:5.3.0`), without specifying `-p`, will not publish this port to your host operating system. You can confirm this by typing `docker port <container_id>`.

The following article, as well as the official [docker engine documentation for expose](https://docs.docker.com/engine/reference/builder/#expose) may be helpful: http://stackoverflow.com/questions/22111060/difference-between-expose-and-publish-in-docker

**Comment by barseghyanartur** [comment]
@dliappis:

Thanks for your answer. It's not the ports that need to be exposed (that part works well), but the host being passed (-e "http.host=0.0.0.0" -e "transport.host=127.0.0.1"). I need to test Elastic and therefore I do need an address to point to. However, since address is picked randomly (when running docker with no arguments provided), it's impossible to establish connection with Elastic. That's why I need to have it running on localhost/127.0.0.1.

See the [Dockerfile here](https://github.com/Goldmund-Wyldebeast-Wunderliebe/docker-python-3.6.0-jessie-nodejs/tree/java-8-elasticsearch-2.x).

**Comment by dliappis** [comment]
@barseghyanartur I am not 100% sure where you need to access elasticsearch from. If it's from the host where you are executing `docker run`, if you do not supply any `-p` parameters it won't be accessible at all from it (you can verify this with `docker port <containerId>`).

If you are trying to access elasticsearch from another container, say by using [legacy links](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/) or the new [bridge network](https://docs.docker.com/engine/userguide/networking/) then that container can access elasticsearch with the `<containername:9200>` as done with our own [acceptance tests](https://github.com/elastic/elasticsearch-docker/blob/5.3/tests/es_acceptance.py#L21), where the first elasticsearch node is given a [link alias](https://github.com/elastic/elasticsearch-docker/blob/master/docker-compose.yml#L65-L66).

I looked at your [Dockerfile](https://github.com/Goldmund-Wyldebeast-Wunderliebe/docker-python-3.6.0-jessie-nodejs/blob/java-8-elasticsearch-2.x/Dockerfile) and it is not based on the code used for the Elasticsearch Docker image code in this repo: https://github.com/elastic/elasticsearch-docker . It rather resembles the code used in the [image created by Docker Inc](https://github.com/docker-library/elasticsearch/blob/391a5a9ba2836175f68c9c2d3655825300e4585e/5/Dockerfile).

To be able to help you more effectively, I suggest you start basing your work on the code in this repo (also have a look at the examples [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_c_customized_image) to avoid replication).
