### ISSUE TITLE
Hot-Warm Architecture

### ISSUE THREAD

**Issue by Madhu1512** [elastic/elasticsearch-docker#6]
How do we create Hot-warm architecture with dedicated Master, Client and Data Nodes using official docker image? Any instructions will be helpful.

**Comment by dliappis** [comment]
@Madhu1512 This would not be different from what you would do with the non dockerized version of Elasticsearch. The different node types are described in: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/modules-node.html

Setting those parameters can be done as described with bind mounts as described [in the LDAP/AD issue](https://github.com/elastic/elasticsearch-docker/issues/5#issuecomment-250112710) or by overriding the CMD. Stay tuned for the possibility to define parameter through docker environment variables, this is coming soon!

**Comment by dliappis** [comment]
Closing to keep things tidy. Please re-open if you need any more help.
