### ISSUE TITLE
Windows based image

### ISSUE THREAD

**Issue by ChiefWiggum** [elastic/elasticsearch-docker#61]
It would be awesome if we could get a docker image that is based on windows server images instead of CentOS.
See here for a PR for the deprecated docker-library es repo: [https://github.com/docker-library/elasticsearch/pull/151](https://github.com/docker-library/elasticsearch/pull/151)

**Comment by jarpy** [comment]
We don't have a native Windows container on the road map for Elasticsearch, sorry.

We do plan to ship a Windows container for Winlogbeat, so based on what we learn there, we may consider  extending support to other platforms.
