### ISSUE TITLE
When I use v5.3.2, throw `/bin/sh: yum: not found`

### ISSUE THREAD

**Issue by charleslxh** [elastic/elasticsearch-docker#62]
I try to install `unzip` and `zip` with `RUN yum install -y zip unzip`
but it throw `/bin/sh: yum: not found`,
and in v5.4.0, it works.

**Comment by jarpy** [comment]
Hi. With version 5.4.0, we switched from Alpine Linux to CentOS as the base image.

For version 5.3.2 (which is based on Alpine), you'll want:

``` bash
apk update && apk add zip unzip
```
