### ISSUE TITLE
Elasticsearch configuration for docker bridge

### ISSUE THREAD

**Issue by butterflyinfly** [elastic/elasticsearch-docker#65]
Hello to everyone!
I'm trying to change the current configuration of ELK cluster from docker host mode into docker bridge and faced with some problems.
According to the documentation: https://www.elastic.co/blog/docker-networking when I run elasticsearch in bridge mode, I need to provide the following configuration:

"When running Elasticsearch, you will need to ensure it publishes to an IP address that is reachable from outside the container; this can be configured via the setting network.publish_host.
For the discovery between the nodes you have to configure Zen Discovery via the settings discovery.zen.ping.unicast.hosts and discovery.zen.minimum_master_nodes."
Example:

docker run -d -p 9200:9200 -p 9300:9300 elasticsearch:2 
elasticsearch 
-Des.discovery.zen.ping.unicast.hosts=192.168.99.100,192.168.99.101 
-Des.discovery.zen.minimum_master_nodes=2 
-Des.network.publish_host=192.168.99.100
docker run -d -p 9200:9200 -p 9300:9300 elasticsearch:2 
elasticsearch 
-Des.discovery.zen.ping.unicast.hosts=192.168.99.100,192.168.99.101 
-Des.discovery.zen.minimum_master_nodes=2 
-Des.network.publish_host=192.168.99.101

We need to run elasticsearch on each node. So when I start a cluster with 3 nodes, it looks ok, I can provide needed zen parameters. But if the cluster scale up, how will old nodes know about a new one? New ip-addresses should be added to the Des.discovery.zen.ping.unicast.hosts of currently running dockers with elasticsearch.

Could you please clarify to me how the configuration should be set up? All docker containers are under Marathon control.

Thanks,
Olga

**Comment by xeraa** [comment]
`discovery.zen.ping.unicast.hosts` only provides a seed list ([docs for the parameter](https://www.elastic.co/guide/en/elasticsearch/reference/master/important-settings.html#unicast.hosts)) during initial discovery. As long as one of the seeded nodes is available it will connect you to all other nodes.

For smaller setups (which often don't change that much) you can just provide a list of all the nodes. For larger setups it is common to have 3 dedicated master nodes; then you'd normally configure those.

**Comment by dliappis** [comment]
Hello @butterflyinfly and thank you for your interest.

On top of what @xeraa mentioned, note that the image you are using, [elasticsearch:2](https://hub.docker.com/_/elasticsearch/) is not maintained by Elastic and not related with the code in this repo.
The blog article you linked (https://www.elastic.co/blog/docker-networking) predates the [Elastic Docker images](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) and Elasticsearch 5.
With that said, currently Elastic doesn't produce Docker images for Elasticsearch version 2 but instead strives to produce high quality images from version 5 onwards.

To the core of your question, :+1: to the answer of @xeraa, I tried your config in a Vagrant environment comprising three hosts where all `docker run` commands specified the same fixed pair of IPs as unicast hosts (i.e. the IP address of the first two nodes only) whereas `network.publish_host` defined the IP address of the underlying host and it worked as expected.
