### ISSUE TITLE
image not found with docker pull docker.elastic.co/elasticsearch/elasticsearch:5.4.2

### ISSUE THREAD

**Issue by bargitta** [elastic/elasticsearch-docker#66]
* Docker image used  17.03.1-ce
* Operating System win10
* `docker info` output
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: LEP2:W7QN:SJML:IXU5:SYUT:VHSD:VLTM:LWDD:LWXN:HEPJ:QFXI:JPBK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 38
 System Time: 2017-06-02T02:57:24.0633138Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

## Bug Description

when running docker pull docker.elastic.co/elasticsearch/elasticsearch:5.4.2
the image cannot be found

**Comment by jarpy** [comment]
Hi,

The latest version of Elasticsearch is version 5.4.1.

https://www.elastic.co/downloads/elasticsearch
