### ISSUE TITLE
Stopped by offline reasons

### ISSUE THREAD

**Issue by francescobianco** [elastic/elasticsearch-docker#68]
I'm NOT able to PULL this image 
docker.elastic.co/elasticsearch/elasticsearch
on official elastic hosting

Why we have leave DockerHUB??? Why??? Mirroring is the best approch!!

**Comment by dliappis** [comment]
There is no `:latest` tag for the images. This is deliberate to deter users from running clusters with mismatched versions in production.

Please use one of the released versions of Elasticsearch as a tag. The latest can be always in : https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html which is `docker.elastic.co/elasticsearch/elasticsearch:5.4.1`.
