### ISSUE TITLE
Discovery Plugins

### ISSUE THREAD

**Issue by Madhu1512** [elastic/elasticsearch-docker#7]
How do we install discovery plugins(AWS, Auzure etc..) in to the docker image?

**Comment by jeredding** [comment]
My suggestion off-the-cuff is to use the Docker image as the base of your image, using something like `FROM docker.elastic.co/elasticsearch/elasticsearch` and then install plugin(s) using `RUN` command(s).

**Comment by dliappis** [comment]
Closing to keep things tidy. Please re-open if you need any more help.
