### ISSUE TITLE
Some environment variables are not passed to elasticsearch

### ISSUE THREAD

**Issue by bquartier** [elastic/elasticsearch-docker#71]
Hi,

## Bug Description
Some env variable are not passed to Elasticsearch. For example, if I run:

```shell
$ docker run -it -p 9300:9200 \n
    -e "thread_pool.bulk.queue_size=500" \n
    -e "cluster.name=hey" \n
    -e "http.host=0.0.0.0" \n
    -e "transport.host=127.0.0.1" \n 
    docker.elastic.co/elasticsearch/elasticsearch:5.4.1
```
the variable thread_pool.bulk.queue_size is not set to 500 while cluster.name is correctly set to "hey".
```shell
$ curl -s 'localhost:9300/_cluster/health?pretty'
{
  "cluster_name" : "hey",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 3,
  "active_shards" : 3,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 3,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 50.0
}
```
```shell
$  $ curl -s 'localhost:9300/_cat/thread_pool/bulk?v&h=queue_size'
queue_size
       200
```
Do I miss something?

Without digging deeper, it seems to me that https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/bin/es-docker#L16 may not match variable with an '_' in their name.

Benoît

**Comment by dliappis** [comment]
Thanks for raising this! I think you found the issue here, the character class in https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/bin/es-docker#L16 won't permit/pass an underscope character in those env vars.

I will adjust, add a test case for this and backport as required.

**Comment by bquartier** [comment]
Great.

What about versioning? Will you republish a docker.elastic.co/elasticsearch/elasticsearch:5.4.1 ?

**Comment by dliappis** [comment]
@bquartier Sure thing. Expect one today, soonish, will update here.

**Comment by dliappis** [comment]
Backported to 5.4.1/5.4.0 and 5.3.3.

**Comment by bquartier** [comment]
Nice, thank you for your this correction, that was fast!
