### ISSUE TITLE
LDAP integration

### ISSUE THREAD

**Issue by karampuri** [elastic/elasticsearch-docker#74]
Hi,

 How to configure LDAP integration with search guard in elastic search.
i followed below link
https://github.com/floragunncom/search-guard-docs/blob/master/ldap.md
please assist me.

**Comment by xeraa** [comment]
Hey,

Thanks for reaching out!
Unfortunately this is the wrong place — we don't have any association with SearchGuard. Actually it's a competing product and we have [LDAP support in X-Pack](https://www.elastic.co/guide/en/x-pack/current/ldap-realm.html) as well if you are looking for a solution supported by us ;-)
