### ISSUE TITLE
Alpine Image

### ISSUE THREAD

**Issue by marii-moe** [elastic/elasticsearch-docker#76]
## Feature Description

Any chance there will be an alpine image created for elastic search?

**Comment by xeraa** [comment]
Thanks for reaching out!

Actually we've started with Alpine, but it [didn't work out that well](https://www.elastic.co/blog/docker-base-centos7), so at the moment we've standardized on CentOS 7.

But to understand this better in general: What's your motivation for an Alpine based image?
Closing for now, but if you have a particular reason, please add it.

**Comment by dynamiccast** [comment]
I would be interested just to save disk space.

docker.elastic.co/elasticsearch/elasticsearch:5.4.3 is 548MB
Soon to be deprecated docker elaticsearch:5.4.3-alpine is 123MB

**Comment by petk** [comment]
+1 Alpine based one would be really awesome addition.

Elasticsearch 5.6.3 based on CentOS 657MB
Elasticsearch 5.6.3 based on Debian 580MB
Alpine based image 123MB

**Comment by dliappis** [comment]
@petk There are concrete technical reasons that prevent us from supporting Alpine; some of the argumentation can be found in https://www.elastic.co/blog/docker-base-centos7

Having said that, there are things we are working on to make the image size smaller for 6.0.0, including multi-stage builds, a customized centos:7 base with jre preinstalled, without additional layers attributed to `yum -y update` so stay tuned!

**Comment by csandanov** [comment]
It seems the [reported issue](https://bugs.alpinelinux.org/issues/7093) in Alpine has been fixed a while ago. I've personally been running [alpine-based image](https://github.com/wodby/elasticsearch) (openjdk 8) for over a year now and it seems to be working fine

**Comment by petk** [comment]
Worth noting, there is also a package [elasticsearch](https://pkgs.alpinelinux.org/packages?name=elasticsearch&branch=v3.8) in Alpine official repository.
