### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/elasticsearch-docker#77]
There a few Kubernetes configs out there and associated lifecycle hook script (ie. wait until all shards move away from container on shutdown). Is there any appetite for including them here, where they would benefit from more review?

I'm thinking things like:
https://github.com/kubernetes/kubernetes/issues/3595#issuecomment-287692878
https://github.com/jetstack/elasticsearch-pet/blob/master/pre-stop-hook.sh

**Comment by jarpy** [comment]
I can certainly see things like this being useful, but I'm not sure we want to include them here. Right now, the maintainers of this repository (@dliappis and me) aren't in a position to provide first-class support for Kubernetes-specific features.  The current scope of this repo is to provide good quality images that are orchestrator agnostic.

This does give us something to keep in mind if we extend our efforts specifically to Kubernetes though. So, thanks for the suggestion.
