### ISSUE TITLE
Write audit logs to stdout/docker log instead of a file inside the container

### ISSUE THREAD

**Issue by jakommo** [elastic/elasticsearch-docker#78]
When [enabling audit logging in x-pack](https://www.elastic.co/guide/en/x-pack/current/auditing.html), this is written to `/usr/share/elasticsearch/logs/elasticsearch_access.log` inside the container. 
Proposing to adjust `config/x-pack/log4j2.properties` to write to `stdout` as we do with the normal elasticsearch logs.

**Comment by jarpy** [comment]
Absolutely. I'd go so far as to call this a bug.

**Comment by jarpy** [comment]
The patch above seems to do the trick.

```
$ docker run --rm -it -p9200:9200 -e xpack.security.audit.enabled=true docker.elastic.co/elasticsearch/elasticsearch:5.4.3
[2017-07-03T05:42:27,826][INFO ][o.e.n.Node               ] [] initializing ...
<<< snip >>>
2017-07-03T05:42:33,497][INFO ][o.e.l.LicenseService     ] [gfK-0Qv] license [6460bc0c-0f68-4cab-9042-f56028d7c7f0] mode [trial] - valid
[2017-07-03T05:42:33,860][INFO ][o.e.x.s.a.l.LoggingAuditTrail] [rest] [anonymous_access_denied]        origin_address=[172.17.0.1], uri=[/]
```

**Comment by djschny** [comment]
I'm trying to figure out which images have this patch/fix included in them, but am having trouble as there appears to be no labels or milestones calling this out. Any suggestions on how to keep track of this for the docker image?

**Comment by dliappis** [comment]
@djschny In all versions >=5.5.0

**Comment by kostasb** [comment]
The audit logging destination change (stdout instead of logfile) applied with [PR#79](https://github.com/elastic/elasticsearch-docker/pull/79) seems to only work for the elasticsearch-platinum images. The plain elasticsearch one still uses the logfile configuration.

See below for the x-pack log4j2.properties shipped with the elasticsearch:6.2.2 image

```
docker run -e ELASTIC_PASSWORD=MagicWord -e xpack.security.audit.enabled=true docker.elastic.co/elasticsearch/elasticsearch:6.2.2
```

```
sh-4.2# cd /usr/share/elasticsearch/config/x-pack/

sh-4.2# cat log4j2.properties 
appender.audit_rolling.type = RollingFile
appender.audit_rolling.name = audit_rolling
appender.audit_rolling.fileName = ${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}_access.log
appender.audit_rolling.layout.type = PatternLayout
appender.audit_rolling.layout.pattern = [%d{ISO8601}] %m%n
appender.audit_rolling.filePattern = ${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}_access-%d{yyyy-MM-dd}.log
appender.audit_rolling.policies.type = Policies
appender.audit_rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.audit_rolling.policies.time.interval = 1
appender.audit_rolling.policies.time.modulate = true

logger.xpack_security_audit_logfile.name = org.elasticsearch.xpack.security.audit.logfile.LoggingAuditTrail
logger.xpack_security_audit_logfile.level = info
logger.xpack_security_audit_logfile.appenderRef.audit_rolling.ref = audit_rolling
logger.xpack_security_audit_logfile.additivity = false

logger.xmlsig.name = org.apache.xml.security.signature.XMLSignature
logger.xmlsig.level = error
logger.samlxml_decrypt.name = org.opensaml.xmlsec.encryption.support.Decrypter
logger.samlxml_decrypt.level = fatal
logger.saml2_decrypt.name = org.opensaml.saml.saml2.encryption.Decrypter
logger.saml2_decrypt.level = fatal

```

There have been [reports](https://discuss.elastic.co/t/security-audit-logs-not-printing-to-console-with-docker/119307) from users stepping on this and being surprised by the inconsistency in the config.

Any idea why the elasticsearch images are currently using different log4j options to elasticsearch-platinum ones @dliappis @jarpy  ?

**Comment by kostasb** [comment]
Until the audit logging-to-stdout config is ported over to the elasticsearch image, here is a workaround provided by @dliappis 

Create a file on the physical filesystem with the logging config sending audit logs to stdout, e.g. named stdout_log4j2.properties:

logger.xpack_security_audit_logfile.name = org.elasticsearch.xpack.security.audit.logfile.LoggingAuditTrail
logger.xpack_security_audit_logfile.appenderRef.console.ref = console
logger.xpack_security_audit_logfile.level = info

Make sure the uid/gid ownership of the file provide read permission for the docker daemon and the ES process.

Then use docker's -v argument to override the configuration file inside the container, with the file from the physical filesystem, e.g.:

docker run -e ELASTIC_PASSWORD=MagicWord -v /path/to/stdout_log4j2.properties:/usr/share/elasticsearch/config/x-pack/log4j2.properties -e xpack.security.audit.enabled=true docker.elastic.co/elasticsearch/elasticsearch:6.2.2

**Comment by jarpy** [comment]
> Any idea why the elasticsearch images are currently using different log4j options to elasticsearch-platinum ones @dliappis @jarpy ?

It's conditional on the `platinum` image, you're right:
https://github.com/elastic/elasticsearch-docker/blob/master/templates/Dockerfile.j2#L80,L82

I thought that audit logging was a feature of X-Pack security, and thus not available with a basic licence. Are people running the basic image and then adding their own licence for Gold/Platinum?

**Comment by kostasb** [comment]
With the elasticsearch image running the "basic" license, xpack security and auditing are both enabled:

> "xpack.security.enabled" : "true"
"xpack.security.audit.enabled" : "true"

You can find these settings with

```
curl -X GET "localhost:9200/_cluster/settings?include_defaults&pretty&flat_settings"
```

This denies access for the user to the /_xpack/security endpoints but may generate some audit logging from the transport.

```
[2018-02-22T07:36:22,794] [transport] [access_granted]	origin_type=[local_node], origin_address=[172.17.0.2], principal=[_xpack_security], roles=[superuser], action=[cluster:admin/xpack/security/realm/cache/clear], request=[ClearRealmCacheRequest]
```

It has also been observed that users sometimes start with the basic image and then as they move forward they apply gold or platinum licenses over it.

**Comment by pgomulka** [comment]
Hey, this should be fixed in next release. 7.3, 7.2.1 and 8
https://github.com/elastic/elasticsearch/pull/42671
