### ISSUE TITLE
latest tag

### ISSUE THREAD

**Issue by bitgandtter** [elastic/elasticsearch-docker#83]
## Feature Description
There is any particular reason for not to have a `latest` tag? It will be nice to have it so we don't need to keep changing our stacks just rolling a new release will be fine. Excuse my ignorance if there is an strong reason for it besides restrict versions.

**Comment by drewr** [comment]
We've [answered this before](https://github.com/elastic/elasticsearch-docker/issues/75#issuecomment-310421763), but the short of it is that it's bad practice and we don't want to support it. It may not be so in your case, but "just rolling a new release" can have huge implications on many users. Best thing to do is thread the version through your code and when there's a release you want to get to, just set bump that parameter. You can measure your own risk that way.
