### ISSUE TITLE
Can't pull official images

### ISSUE THREAD

**Issue by StarpTech** [elastic/elasticsearch-docker#89]
`docker-compose up`
```
Error response from daemon: Get https://docker.elastic.co/v2/: dial tcp: lookup docker.elastic.co on [::1]:53: read udp [::1]:51036->[::1]:53: read: connection ref
used
```

https://docker.elastic.co/v2/ returns
```
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

**Comment by dliappis** [comment]
Can you share the content of your docker-compose file?

As a quick check on your side, does `docker pull docker.elastic.co/elasticsearch/elasticsearch:5.5.0` work?

The available images and tags can be seen at www.docker.elastic.co

**Comment by StarpTech** [comment]
I use the same file in this repo.

```
E:\Repositorys\docker-elk [master ≡]> docker pull docker.elastic.co/elasticsearch/elasticsearch:5.5.0
Error response from daemon: Get https://docker.elastic.co/v2/: dial tcp: lookup docker.elastic.co on [::1]:53: read udp [::1]:48945->[::1]:53: read: connection ref
used
```

**Comment by dliappis** [comment]
Looking a bit closer, I wonder if your machine/server has no IPv4 address. At the moment, `docker.elastic.co` does not support IPv6.

**Comment by StarpTech** [comment]
WOOT  :expressionless: thanks for clarifying.

**Comment by mcafeerun** [comment]
Hi, @dliappis, 
Any work around for this issue? 
```
docker pull docker.elastic.co/elasticsearch/elasticsearch:6.2.2
Pulling repository docker.elastic.co/elasticsearch/elasticsearch
unauthorized: authentication required
```

**Comment by jarpy** [comment]
Hi,

That particular image is also mirrored to Docker Hub now, so you could try:

```
docker pull elastic/elasticsearch:6.2.2
```

**Comment by jarpy** [comment]
You're correct, this is just a workaround, sorry.

We have a real fix on our roadmap, but it's a pretty big fix. We need to move our container registry into an environment with comprehensive IPv6 support. It's currently hosted in a place where IPv6 is pretty limited.
