### ISSUE TITLE
Build also logstash docker images

### ISSUE THREAD

**Issue by agonzalezm** [elastic/elasticsearch-docker#9]
## Feature Description

You have elasticsearch-docker and kibana-docker images, could you also provide logstash-docker images? I think is great to have full stack docker images for testing things.

**Comment by viztastic** [comment]
+1

**Comment by dliappis** [comment]
This is something on our roadmap and we will be providing a logstash docker image as well. Stay tuned for more news! cc @jarpy

**Comment by agonzalezm** [comment]
Looks like you already realeased this and logstash docker image is available at:
https://github.com/elastic/logstash-docker

Thanks!

**Comment by dliappis** [comment]
@agonzalezm Note that the logstash image is still WiP; stay tuned on our blog page https://www.elastic.co/blog where the availability of the image will be announced once ready. Thanks for your interest!

**Comment by jarpy** [comment]
Yes. It's still in development, but we're doing everything "in the open". Come on over to [the project page](https://github.com/elastic/logstash-docker) if you'd like to join the conversation.
